#第一个数据源（多数据源将会在后面介绍,primary表示为第一个数据源）
spring: 
   jpa: 
      show-sql: true
      hibernate:
         # Hibernate ddl auto (create, create-drop, update)
         ddl-auto: update
         #spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect  
         naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy  
      #spring.jpa.database=org.hibernate.dialect.MySQL5InnoDBDialect 
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
   datasource: 
      primary: 
         dataSourceProperties: 
            characterEncoding: utf-8
            serverName: localhost
            portNumber: 3306
            databaseName: se
         dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
         username: root
         password: 123456
      # 下面为连接池的补充设置，应用到上面所有数据源中
      default-auto-commit: true #自动提交
      auto-commit: true#指定updates是否自动提交
      maximum-pool-size: 100
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
      time-between-eviction-runs-millis: 18800
      # 配置一个连接在池中最小生存的时间，单位是毫秒 
      minEvictableIdleTimeMillis: 300000